"""Plotting utilities for spin-chain SDP relaxation results.

This module provides functions to visualize results from saved artifacts
(generated by scripts in spins_sdp/scripts/) without recomputing anything.

Main plotting functions:
  - plot_exact_vs_lb: Compare exact ground energy vs moment-relaxation lower bound
  - plot_heisenberg_exact_vs_lb: Heisenberg chain comparison (paper Case B style)
  - plot_heisenberg_j2_sweep: Heisenberg-J2 chain sweep over J2 values (paper Case C style)
  - plot_runtime_comparison: Compare solve times across methods/levels

Utility functions:
  - npa_basis_size_heatmap: Visualize NPA basis size vs N and level
  - plot_basis_size_comparison: Compare basis sizes across methods
"""

from __future__ import annotations

from typing import Optional, Dict, Any, Iterable, Tuple, List, Mapping, overload
from pathlib import Path
import json

from matplotlib.ticker import MaxNLocator
import numpy as np
import matplotlib.pyplot as plt

from spins_sdp.basis_builder import generate_npa_basis, generate_heisenberg_paper_basis


# =============================================================================
# Artifact discovery helpers
# =============================================================================

def _default_results_root() -> Path:
    """Default location for saved artifacts: spins_sdp/results."""
    return Path(__file__).resolve().parent / "spins_sdp" / "results"


def _iter_run_dirs(results_root: Path, artifact: str, schema_version: int) -> Iterable[Path]:
    """Iterate over run directories for a given artifact type."""
    base = results_root / artifact / f"v{schema_version}"
    if not base.exists():
        return []
    return [p for p in base.iterdir() if p.is_dir()]


def _load_meta(run_dir: Path) -> Dict[str, Any]:
    """Load meta.json from a run directory."""
    meta_path = run_dir / "meta.json"
    if not meta_path.exists():
        raise FileNotFoundError(f"Missing meta.json in {run_dir}")
    return json.loads(meta_path.read_text(encoding="utf-8"))


def _load_npz(run_dir: Path) -> Dict[str, np.ndarray]:
    """Load data.npz from a run directory."""
    data_path = run_dir / "data.npz"
    if not data_path.exists():
        raise FileNotFoundError(f"Missing data.npz in {run_dir}")
    with np.load(data_path, allow_pickle=False) as data:
        return {k: data[k] for k in data.files}


def _values_close(a: Any, b: Any, *, atol: float = 1e-12) -> bool:
    """Check if two values are close (for float comparison in meta matching)."""
    if isinstance(a, (int, str, bool)) or a is None:
        return a == b
    if isinstance(a, float) or isinstance(b, float):
        try:
            return abs(float(a) - float(b)) <= atol
        except Exception:
            return a == b
    return a == b


def _meta_matches_query(meta: Any, query: Any) -> bool:
    """Return True if `query` is a subset of `meta` (recursive for dicts)."""
    if isinstance(query, Mapping):
        if not isinstance(meta, Mapping):
            return False
        for k, v in query.items():
            if k not in meta:
                return False
            if not _meta_matches_query(meta[k], v):
                return False
        return True
    if isinstance(query, list):
        return meta == query
    return _values_close(meta, query)


def _pick_latest_run(run_dirs: List[Path]) -> Path:
    """Pick the most recently updated run from a list of candidates."""
    def key(p: Path) -> Tuple[str, str]:
        try:
            m = _load_meta(p)
            return (str(m.get("updated_at", "")), str(m.get("created_at", "")))
        except Exception:
            return ("", "")
    return max(run_dirs, key=key)


def _find_run_dir(
    *,
    results_root: Path,
    artifact: str,
    schema_version: int,
    run_hash: Optional[str] = None,
    meta_query: Optional[Dict[str, Any]] = None,
) -> Path:
    """Find a run directory by hash or by matching meta.json fields."""
    if run_hash is not None:
        run_dir = results_root / artifact / f"v{schema_version}" / run_hash
        if not run_dir.exists():
            raise FileNotFoundError(f"No run dir: {run_dir}")
        return run_dir

    if meta_query is None:
        raise ValueError("Provide either run_hash or meta_query")

    candidates: List[Path] = []
    for run_dir in _iter_run_dirs(results_root, artifact, schema_version):
        try:
            meta = _load_meta(run_dir)
        except Exception:
            continue
        if _meta_matches_query(meta, meta_query):
            candidates.append(run_dir)

    if len(candidates) == 0:
        base = results_root / artifact / f"v{schema_version}"
        raise FileNotFoundError(
            f"No matching run found under {base}. "
            f"Generate the data with the scripts first."
        )
    if len(candidates) == 1:
        return candidates[0]
    return _pick_latest_run(candidates)


# =============================================================================
# Main plotting functions (artifact-based)
# =============================================================================

@overload
def plot_exact_vs_lb(
    *,
    exact_hash: str,
    lb_hash: str,
    results_root: Optional[Path] = None,
    per_site: bool = False,
    Ns: Optional[Iterable[int]] = None,
    show: bool = True,
    save_path: Optional[Path] = None,
) -> Dict[str, Any]:
    ...


@overload
def plot_exact_vs_lb(
    *,
    model: str,
    model_params: Dict[str, float],
    boundary: str = "periodic",
    lb_basis: str = "npa",
    npa_level: int = 1,
    results_root: Optional[Path] = None,
    per_site: bool = False,
    Ns: Optional[Iterable[int]] = None,
    show: bool = True,
    save_path: Optional[Path] = None,
) -> Dict[str, Any]:
    ...


def plot_exact_vs_lb(
    *,
    model: Optional[str] = None,
    model_params: Optional[Dict[str, float]] = None,
    boundary: str = "periodic",
    per_site: bool = False,
    Ns: Optional[Iterable[int]] = None,
    exact_hash: Optional[str] = None,
    lb_hash: Optional[str] = None,
    lb_basis: str = "npa",
    npa_level: int = 1,
    results_root: Optional[Path] = None,
    show: bool = True,
    save_path: Optional[Path] = None,
) -> Dict[str, Any]:
    """Plot exact energy vs moment-relaxation lower bound from saved artifacts.

    Two call styles:
      1) Hash-based: provide `exact_hash` and `lb_hash` only.
      2) Param-based: provide `model`, `model_params`, `boundary`, etc.

    Args:
        model: Model name ("ising", "heisenberg", "heisenberg_j2").
        model_params: Model parameters dict (e.g., {"J": 1.0, "h": 0.7, "k": 0.3}).
        boundary: "periodic" or "open".
        per_site: If True, plot energy per site (E/N).
        Ns: Filter to these N values only.
        exact_hash: Explicit hash for exact run.
        lb_hash: Explicit hash for LB run.
        lb_basis: Basis used for LB ("npa", "heisenberg_simple", etc.).
        npa_level: NPA level k (only meaningful when lb_basis="npa").
        results_root: Override default results directory.
        show: Whether to call plt.show().
        save_path: If provided, save figure to this path.

    Returns:
        Dict with run directories, arrays (N, E0, E_lb, gap), and figure/axes.
    """
    results_root = results_root or _default_results_root()

    if lb_basis != "npa" and npa_level != 1:
        raise ValueError("`npa_level` is only valid when lb_basis='npa'.")

    if (exact_hash is None or lb_hash is None) and (model is None or model_params is None):
        raise ValueError(
            "Provide either `exact_hash` and `lb_hash` (hash-based lookup) "
            "or `model` and `model_params` (param-based lookup)."
        )

    # --- Exact run lookup ---
    exact_query = None
    if exact_hash is None:
        assert model is not None and model_params is not None
        exact_query = {
            "artifact": "spin_exact_ground_energy",
            "schema_version": 1,
            "model": model,
            "method": "exact_diagonalization",
            "params": {k: float(v) for k, v in model_params.items()},
            "boundary": boundary,
        }
    exact_run = _find_run_dir(
        results_root=results_root,
        artifact="spin_exact_ground_energy",
        schema_version=1,
        run_hash=exact_hash,
        meta_query=exact_query,
    )

    # --- LB run lookup ---
    lb_query = None
    if lb_hash is None:
        assert model is not None and model_params is not None
        lb_query = {
            "artifact": "spin_moment_energy_lb",
            "schema_version": 1,
            "model": model,
            "method": "pauli_moment_relaxation",
            "params": {k: float(v) for k, v in model_params.items()},
            "boundary": boundary,
            "basis": lb_basis,
            "sense": "min",
        }
        if lb_basis == "npa":
            lb_query["npa_level"] = int(npa_level)
    lb_run = _find_run_dir(
        results_root=results_root,
        artifact="spin_moment_energy_lb",
        schema_version=1,
        run_hash=lb_hash,
        meta_query=lb_query,
    )

    exact_meta = _load_meta(exact_run)
    lb_meta = _load_meta(lb_run)

    # Infer model from meta if using hash-based lookup
    if model is None:
        model = str(exact_meta.get("model", lb_meta.get("model", "unknown")))
    if model_params is None:
        mp = exact_meta.get("params")
        model_params = mp if isinstance(mp, dict) else {}

    # Validate consistency
    meta_model_exact = exact_meta.get("model")
    meta_model_lb = lb_meta.get("model")
    if meta_model_exact is not None and str(meta_model_exact) != str(model):
        raise ValueError(f"Exact run model={meta_model_exact!r} does not match {model!r}")
    if meta_model_lb is not None and str(meta_model_lb) != str(model):
        raise ValueError(f"LB run model={meta_model_lb!r} does not match {model!r}")

    meta_basis = lb_meta.get("basis")
    if meta_basis is not None and str(meta_basis) != str(lb_basis):
        raise ValueError(f"LB run basis={meta_basis!r} does not match {lb_basis!r}")

    if lb_basis == "npa":
        meta_npa_level = lb_meta.get("npa_level")
        if meta_npa_level is None:
            raise ValueError(
                "LB run meta.json missing `npa_level`. "
                "Regenerate artifacts with updated scripts."
            )
        if int(meta_npa_level) != int(npa_level):
            raise ValueError(
                f"LB run npa_level={meta_npa_level} does not match {npa_level}"
            )

    # --- Load data ---
    exact_npz = _load_npz(exact_run)
    lb_npz = _load_npz(lb_run)

    N_exact = np.asarray(exact_npz["N"], dtype=int)
    E0 = np.asarray(exact_npz["E0"], dtype=float)
    N_lb = np.asarray(lb_npz["N"], dtype=int)
    E_lb = np.asarray(lb_npz["E_lb"], dtype=float)

    # Filter by Ns if provided
    if Ns is not None:
        Ns_set = set(int(n) for n in Ns)
        mask_ex = np.array([int(n) in Ns_set for n in N_exact], dtype=bool)
        mask_lb = np.array([int(n) in Ns_set for n in N_lb], dtype=bool)
        N_exact, E0 = N_exact[mask_ex], E0[mask_ex]
        N_lb, E_lb = N_lb[mask_lb], E_lb[mask_lb]

    # Sort by N
    ex_order = np.argsort(N_exact)
    lb_order = np.argsort(N_lb)
    N_exact, E0 = N_exact[ex_order], E0[ex_order]
    N_lb, E_lb = N_lb[lb_order], E_lb[lb_order]

    # Compute gap on overlap
    overlap = sorted(set(int(n) for n in N_exact).intersection(int(n) for n in N_lb))
    overlap = np.array(overlap, dtype=int)
    ex_map = {int(n): float(e) for n, e in zip(N_exact, E0)}
    lb_map = {int(n): float(e) for n, e in zip(N_lb, E_lb)}
    gap = np.array([ex_map[int(n)] - lb_map[int(n)] for n in overlap], dtype=float)

    # Prepare plot data
    if per_site:
        E0_plot = E0 / N_exact
        E_lb_plot = E_lb / N_lb
        gap_plot = gap / overlap
        ylabel_e = "Energy per site (E/N)"
        ylabel_gap = "Gap per site (Exact - LB)/N"
    else:
        E0_plot = E0
        E_lb_plot = E_lb
        gap_plot = gap
        ylabel_e = "Energy (E)"
        ylabel_gap = "Gap (Exact - LB)"

    # --- Plotting ---
    fig, axes = plt.subplots(1, 2, figsize=(14, 5))

    axes[0].plot(N_exact, E0_plot, marker="o", linewidth=2, label="Exact")
    if lb_basis == "npa":
        lb_label = f"LB ({lb_basis}, k={int(npa_level)})"
    else:
        lb_label = f"LB ({lb_basis})"
    axes[0].plot(N_lb, E_lb_plot, marker="s", linewidth=2, label=lb_label)
    axes[0].set_xlabel("Number of spins N")
    axes[0].set_ylabel(ylabel_e)
    axes[0].set_title(f"{model}: Exact vs Lower Bound")
    axes[0].grid(True, alpha=0.3)
    axes[0].legend()
    axes[0].xaxis.set_major_locator(MaxNLocator(integer=True))

    axes[1].plot(overlap, gap_plot, marker="^", color="red", linewidth=2)
    axes[1].set_xlabel("Number of spins N")
    axes[1].set_ylabel(ylabel_gap)
    axes[1].set_title("Relaxation Gap (Exact - LB)")
    axes[1].grid(True, which="both", alpha=0.3)
    axes[1].xaxis.set_major_locator(MaxNLocator(integer=True))
    if len(gap_plot) > 0 and np.all(gap_plot > 0):
        axes[1].set_yscale("log")

    plt.tight_layout()
    if save_path is not None:
        plt.savefig(save_path)
    if show:
        plt.show()

    return {
        "exact_run_dir": exact_run,
        "lb_run_dir": lb_run,
        "N_exact": N_exact,
        "E0": E0,
        "N_lb": N_lb,
        "E_lb": E_lb,
        "N_overlap": overlap,
        "gap": gap,
        "figure": fig,
        "axes": axes,
    }

def plot_heisenberg_j2_sweep(
    *,
    N: int,
    J2_values: Iterable[float],
    boundary: str = "periodic",
    per_site: bool = True,
    results_root: Optional[Path] = None,
    show: bool = True,
    save_path: Optional[Path] = None,
    print_table: bool = True,
) -> Dict[str, Any]:
    """Plot Heisenberg-J2 ground state energy vs J2.

    Loads artifacts for a fixed N and multiple J2 values, comparing
    exact diagonalization with SDP lower bounds.

    NOTE: Each J2 value requires separate artifact runs with model="heisenberg_j2"
    and J2 specified in model_params.

    Args:
        N: System size.
        J2_values: J2 coupling values to plot.
        boundary: "periodic" or "open".
        per_site: If True, plot E/N.
        results_root: Override default results directory.
        show: Whether to call plt.show().
        save_path: If provided, save figure to this path.
        print_table: If True, print a summary table.

    Returns:
        Dict with J2 values, energies, and figure.
    """
    results_root = results_root or _default_results_root()
    J2_list = list(J2_values)

    exact_energies = []
    sdp_lbs = []
    bases_used = []

    for J2 in J2_list:
        model_params = {"J2": float(J2)}

        # Choose basis based on J2 regime
        lb_basis = "heisenberg_j2_weak" if J2 <= 1.0 else "heisenberg_j2_strong"
        bases_used.append(lb_basis)

        # Find exact run
        exact_query = {
            "artifact": "spin_exact_ground_energy",
            "schema_version": 1,
            "model": "heisenberg_j2",
            "method": "exact_diagonalization",
            "params": model_params,
            "boundary": boundary,
        }
        try:
            exact_run = _find_run_dir(
                results_root=results_root,
                artifact="spin_exact_ground_energy",
                schema_version=1,
                meta_query=exact_query,
            )
            exact_npz = _load_npz(exact_run)
            N_arr = np.asarray(exact_npz["N"], dtype=int)
            E0_arr = np.asarray(exact_npz["E0"], dtype=float)
            idx = np.where(N_arr == N)[0]
            if len(idx) == 0:
                raise FileNotFoundError(f"No N={N} in exact run for J2={J2}")
            exact_energies.append(float(E0_arr[idx[0]]))
        except FileNotFoundError as e:
            raise FileNotFoundError(
                f"Missing exact run for heisenberg_j2 with J2={J2}. "
                f"Generate it first. Original: {e}"
            )

        # Find LB run
        lb_query = {
            "artifact": "spin_moment_energy_lb",
            "schema_version": 1,
            "model": "heisenberg_j2",
            "method": "pauli_moment_relaxation",
            "params": model_params,
            "boundary": boundary,
            "basis": lb_basis,
            "sense": "min",
        }
        try:
            lb_run = _find_run_dir(
                results_root=results_root,
                artifact="spin_moment_energy_lb",
                schema_version=1,
                meta_query=lb_query,
            )
            lb_npz = _load_npz(lb_run)
            N_arr_lb = np.asarray(lb_npz["N"], dtype=int)
            E_lb_arr = np.asarray(lb_npz["E_lb"], dtype=float)
            idx = np.where(N_arr_lb == N)[0]
            if len(idx) == 0:
                raise FileNotFoundError(f"No N={N} in LB run for J2={J2}")
            sdp_lbs.append(float(E_lb_arr[idx[0]]))
        except FileNotFoundError as e:
            raise FileNotFoundError(
                f"Missing LB run for heisenberg_j2 with J2={J2}, basis={lb_basis}. "
                f"Generate it first. Original: {e}"
            )

    J2_arr = np.array(J2_list, dtype=float)
    exact_arr = np.array(exact_energies, dtype=float)
    lb_arr = np.array(sdp_lbs, dtype=float)
    gap = exact_arr - lb_arr

    # Prepare plot data
    if per_site:
        exact_plot = exact_arr / N
        lb_plot = lb_arr / N
        gap_plot = gap / N
        ylabel = "Energy per site (E/N)"
        ylabel_gap = "Gap per site (Exact - LB)/N"
    else:
        exact_plot = exact_arr
        lb_plot = lb_arr
        gap_plot = gap
        ylabel = "Energy (E)"
        ylabel_gap = "Gap (Exact - LB)"

    # --- Plotting ---
    fig, axes = plt.subplots(1, 2, figsize=(14, 5))

    axes[0].plot(J2_arr, exact_plot, marker="o", linewidth=2, markersize=8, label="Exact")
    axes[0].plot(J2_arr, lb_plot, marker="s", linewidth=2, markersize=8, label="SDP LB")
    axes[0].axvline(x=1.0, color="gray", linestyle="--", alpha=0.5, label="J₂=1 (regime change)")
    axes[0].set_xlabel("Second-neighbor coupling $J_2$")
    axes[0].set_ylabel(ylabel)
    axes[0].set_title(f"Heisenberg-J₂ Chain: Exact vs SDP (N={N})")
    axes[0].grid(True, alpha=0.3)
    axes[0].legend()

    axes[1].plot(J2_arr, gap_plot, marker="^", color="red", linewidth=2, markersize=8)
    axes[1].axvline(x=1.0, color="gray", linestyle="--", alpha=0.5)
    axes[1].set_xlabel("Second-neighbor coupling $J_2$")
    axes[1].set_ylabel(ylabel_gap)
    axes[1].set_title("Relaxation Gap")
    axes[1].grid(True, alpha=0.3)

    plt.tight_layout()
    if save_path is not None:
        plt.savefig(save_path)
    if show:
        plt.show()

    if print_table:
        print("=" * 100)
        print(f"Heisenberg-J₂ Chain (N={N}) - Exact vs SDP Comparison")
        print("=" * 100)
        print(f"{'J2':<10} {'Exact E':<15} {'SDP LB':<15} {'Gap':<15} {'Gap/N':<15} {'Basis':<20}")
        print("-" * 100)
        for i, J2 in enumerate(J2_list):
            print(
                f"{J2:<10.3f} {exact_arr[i]:<15.8f} {lb_arr[i]:<15.8f} "
                f"{gap[i]:<15.8e} {gap[i]/N:<15.8e} {bases_used[i]:<20}"
            )
        print("=" * 100)

    return {
        "N": N,
        "J2": J2_arr,
        "exact_energies": exact_arr,
        "sdp_lbs": lb_arr,
        "gap": gap,
        "bases_used": bases_used,
        "figure": fig,
        "axes": axes,
    }


def plot_runtime_comparison(
    *,
    model: str = "ising",
    model_params: Optional[Dict[str, float]] = None,
    boundary: str = "periodic",
    lb_basis: str = "npa",
    npa_levels: Iterable[int] = (1, 2),
    use: str = "t_avg",
    logy: bool = True,
    Ns: Optional[Iterable[int]] = None,
    results_root: Optional[Path] = None,
    show: bool = True,
    save_path: Optional[Path] = None,
) -> Dict[str, Any]:
    """Compare runtime of exact diagonalization vs SDP relaxation.

    Loads timing data from saved artifacts.

    Args:
        model: Model name.
        model_params: Model parameters.
        boundary: "periodic" or "open".
        lb_basis: Basis for LB.
        npa_levels: NPA levels to compare.
        use: "t_avg" or "t_best".
        logy: Log scale for y-axis.
        Ns: Filter to these N values only.
        results_root: Override default results directory.
        show: Whether to call plt.show().
        save_path: If provided, save figure to this path.

    Returns:
        Dict with timing data and figure.
    """
    results_root = results_root or _default_results_root()
    model_params = model_params or {}
    npa_levels = list(npa_levels)

    # --- Load exact timing data ---
    exact_query = {
        "artifact": "spin_exact_ground_energy",
        "schema_version": 1,
        "model": model,
        "method": "exact_diagonalization",
        "params": {k: float(v) for k, v in model_params.items()},
        "boundary": boundary,
    }
    exact_run = _find_run_dir(
        results_root=results_root,
        artifact="spin_exact_ground_energy",
        schema_version=1,
        meta_query=exact_query,
    )
    exact_npz = _load_npz(exact_run)
    N_exact = np.asarray(exact_npz["N"], dtype=int)
    t_exact = np.asarray(exact_npz.get(use, exact_npz.get("t_avg", np.zeros_like(N_exact))), dtype=float)

    order = np.argsort(N_exact)
    N_exact, t_exact = N_exact[order], t_exact[order]

    Ns_set = None
    if Ns is not None:
        Ns_set = set(int(n) for n in Ns)
        mask = np.array([int(n) in Ns_set for n in N_exact], dtype=bool)
        N_exact, t_exact = N_exact[mask], t_exact[mask]

    # --- Load LB timing data for each level ---
    npa_data: Dict[int, Dict[str, np.ndarray]] = {}
    for lvl in npa_levels:
        lb_query = {
            "artifact": "spin_moment_energy_lb",
            "schema_version": 1,
            "model": model,
            "method": "pauli_moment_relaxation",
            "params": {k: float(v) for k, v in model_params.items()},
            "boundary": boundary,
            "basis": lb_basis,
            "sense": "min",
        }
        if lb_basis == "npa":
            lb_query["npa_level"] = int(lvl)

        lb_run = _find_run_dir(
            results_root=results_root,
            artifact="spin_moment_energy_lb",
            schema_version=1,
            meta_query=lb_query,
        )
        lb_npz = _load_npz(lb_run)
        N_lb = np.asarray(lb_npz["N"], dtype=int)
        t_lb = np.asarray(lb_npz.get(use, lb_npz.get("t_avg", np.zeros_like(N_lb))), dtype=float)

        order = np.argsort(N_lb)
        N_lb, t_lb = N_lb[order], t_lb[order]

        if Ns_set is not None:
            mask = np.array([int(n) in Ns_set for n in N_lb], dtype=bool)
            N_lb, t_lb = N_lb[mask], t_lb[mask]

        npa_data[lvl] = {"N": N_lb, "t": t_lb}

    # --- Plotting ---
    fig, ax = plt.subplots(figsize=(10, 6))

    ax.plot(N_exact, t_exact, marker="o", linewidth=2, label=f"Exact ({use})")
    for lvl in npa_levels:
        d = npa_data[lvl]
        label = f"SDP (k={lvl})" if lb_basis == "npa" else f"SDP ({lb_basis})"
        ax.plot(d["N"], d["t"], marker="s", linewidth=2, label=f"{label} ({use})")

    ax.set_xlabel("Number of spins N")
    ax.set_ylabel("Runtime (seconds)")
    ax.set_title(f"{model}: Runtime Comparison")
    ax.xaxis.set_major_locator(MaxNLocator(integer=True))
    if logy:
        ax.set_yscale("log")
    ax.grid(True, alpha=0.3)
    ax.legend()

    plt.tight_layout()
    if save_path is not None:
        plt.savefig(save_path)
    if show:
        plt.show()

    return {
        "exact": {"N": N_exact, "t": t_exact},
        "npa": npa_data,
        "figure": fig,
        "axes": ax,
    }


# =============================================================================
# Utility / exploratory plots (compute on the fly - no artifacts needed)
# =============================================================================

def npa_basis_size_heatmap(
    N_max: int,
    npa_level_max: int,
    *,
    show: bool = True,
    save_path: Optional[Path] = None,
) -> np.ndarray:
    """Generate a heatmap of NPA basis sizes for varying N and NPA level.

    This computes basis sizes on the fly (fast for small N/levels).

    Args:
        N_max: Maximum number of spins.
        npa_level_max: Maximum NPA level.
        show: Whether to call plt.show().
        save_path: If provided, save figure to this path.

    Returns:
        2D array of basis sizes: sizes[level_idx, N_idx].
    """
    N_values = np.arange(1, N_max + 1)
    levels = np.arange(1, npa_level_max + 1)

    sizes = np.array(
        [[len(generate_npa_basis(N=N, k=lvl).words) for N in N_values] for lvl in levels],
        dtype=int,
    )

    fig, ax = plt.subplots(figsize=(10, 6))
    im = ax.imshow(sizes, origin="lower", aspect="auto", cmap="viridis")

    cbar = plt.colorbar(im, ax=ax)
    cbar.set_label("NPA basis size")

    ax.set_xticks(np.arange(len(N_values)))
    ax.set_xticklabels(N_values)
    ax.set_yticks(np.arange(len(levels)))
    ax.set_yticklabels(levels)
    ax.set_xlabel("Number of spins N")
    ax.set_ylabel("NPA level k")
    ax.set_title("NPA Basis Size vs N and Level")

    # Annotate cells
    threshold = sizes.max() / 2
    for yi, lvl in enumerate(levels):
        for xi, N in enumerate(N_values):
            val = sizes[yi, xi]
            color = "white" if val > threshold else "black"
            ax.text(xi, yi, str(val), ha="center", va="center", color=color, fontsize=8)

    plt.tight_layout()
    if save_path is not None:
        plt.savefig(save_path)
    if show:
        plt.show()

    return sizes


def plot_basis_size_comparison(
    N_values: Iterable[int],
    *,
    npa_levels: Iterable[int] = (1, 2, 3),
    include_paper_basis: bool = True,
    logy: bool = True,
    show: bool = True,
    save_path: Optional[Path] = None,
) -> Dict[str, np.ndarray]:
    """Compare basis sizes of different NPA levels and the Heisenberg paper basis.

    This computes basis sizes on the fly.

    Args:
        N_values: System sizes to compare.
        npa_levels: NPA levels to include.
        include_paper_basis: Whether to include the Heisenberg paper basis.
        logy: Use log scale for y-axis.
        show: Whether to call plt.show().
        save_path: If provided, save figure to this path.

    Returns:
        Dict with N and basis sizes for each method.
    """
    Ns = np.array(list(N_values), dtype=int)
    npa_levels = list(npa_levels)
    result: Dict[str, np.ndarray] = {"N": Ns}

    for lvl in npa_levels:
        sizes = np.array([len(generate_npa_basis(N=N, k=lvl).words) for N in Ns])
        result[f"npa_k{lvl}"] = sizes

    if include_paper_basis:
        paper_sizes = np.array([len(generate_heisenberg_paper_basis(N=N)) for N in Ns])
        result["heisenberg_paper"] = paper_sizes

    # Plot
    fig, ax = plt.subplots(figsize=(10, 6))

    for lvl in npa_levels:
        ax.plot(Ns, result[f"npa_k{lvl}"], marker="o", linewidth=2, label=f"NPA k={lvl}")

    if include_paper_basis:
        ax.plot(Ns, result["heisenberg_paper"], marker="s", linewidth=2, linestyle="--", label="Heisenberg paper")

    if logy:
        ax.set_yscale("log")

    ax.set_xlabel("Number of spins N")
    ax.set_ylabel("Basis size")
    ax.xaxis.set_major_locator(MaxNLocator(integer=True))
    ax.set_title("Basis Size Comparison")
    ax.grid(True, which="both", alpha=0.3)
    ax.legend()

    plt.tight_layout()
    if save_path is not None:
        plt.savefig(save_path)
    if show:
        plt.show()

    return result
