"""Plotting utilities for spin-chain SDP relaxation results.

This module provides functions to visualize results from saved artifacts
(generated by scripts in spins_sdp/scripts/) without recomputing anything.

Main plotting functions:
  - plot_exact_vs_lb: Compare exact ground energy vs moment-relaxation lower bound
  - plot_heisenberg_exact_vs_lb: Heisenberg chain comparison (paper Case B style)
  - plot_heisenberg_j2_sweep: Heisenberg-J2 chain sweep over J2 values (paper Case C style)
  - plot_runtime_comparison: Compare solve times across methods/levels

Optimization sweep plotting functions:
  - plot_optimization_sweep: Plot best lower bound vs k for an optimization sweep
  - plot_optimization_convergence: Plot how bounds improve with more monomials
  - plot_optimization_seeds_comparison: Compare results across different seeds

Utility functions:
  - npa_basis_size_heatmap: Visualize NPA basis size vs N and level
  - plot_basis_size_comparison: Compare basis sizes across methods
"""

from __future__ import annotations

from typing import Optional, Dict, Any, Iterable, Tuple, List, Mapping, overload
from pathlib import Path
import json

from matplotlib.ticker import MaxNLocator
import numpy as np
import matplotlib.pyplot as plt

from spins_sdp.basis_builder import generate_npa_basis, generate_heisenberg_paper_basis


# =============================================================================
# Artifact discovery helpers
# =============================================================================

def _default_results_root() -> Path:
    """Default location for saved artifacts: spins_sdp/results."""
    return Path(__file__).resolve().parent / "spins_sdp" / "results"


def _iter_run_dirs(results_root: Path, artifact: str, schema_version: int) -> Iterable[Path]:
    """Iterate over run directories for a given artifact type."""
    base = results_root / artifact / f"v{schema_version}"
    if not base.exists():
        return []
    return [p for p in base.iterdir() if p.is_dir()]


def _load_meta(run_dir: Path) -> Dict[str, Any]:
    """Load meta.json from a run directory."""
    meta_path = run_dir / "meta.json"
    if not meta_path.exists():
        raise FileNotFoundError(f"Missing meta.json in {run_dir}")
    return json.loads(meta_path.read_text(encoding="utf-8"))


def _load_npz(run_dir: Path) -> Dict[str, np.ndarray]:
    """Load data.npz from a run directory."""
    data_path = run_dir / "data.npz"
    if not data_path.exists():
        raise FileNotFoundError(f"Missing data.npz in {run_dir}")
    with np.load(data_path, allow_pickle=False) as data:
        return {k: data[k] for k in data.files}


def _values_close(a: Any, b: Any, *, atol: float = 1e-12) -> bool:
    """Check if two values are close (for float comparison in meta matching)."""
    if isinstance(a, (int, str, bool)) or a is None:
        return a == b
    if isinstance(a, float) or isinstance(b, float):
        try:
            return abs(float(a) - float(b)) <= atol
        except Exception:
            return a == b
    return a == b


def _meta_matches_query(meta: Any, query: Any) -> bool:
    """Return True if `query` is a subset of `meta` (recursive for dicts)."""
    if isinstance(query, Mapping):
        if not isinstance(meta, Mapping):
            return False
        for k, v in query.items():
            if k not in meta:
                return False
            if not _meta_matches_query(meta[k], v):
                return False
        return True
    if isinstance(query, list):
        return meta == query
    return _values_close(meta, query)


def _pick_latest_run(run_dirs: List[Path]) -> Path:
    """Pick the most recently updated run from a list of candidates."""
    def key(p: Path) -> Tuple[str, str]:
        try:
            m = _load_meta(p)
            return (str(m.get("updated_at", "")), str(m.get("created_at", "")))
        except Exception:
            return ("", "")
    return max(run_dirs, key=key)


def _find_run_dir(
    *,
    results_root: Path,
    artifact: str,
    schema_version: int,
    run_hash: Optional[str] = None,
    meta_query: Optional[Dict[str, Any]] = None,
) -> Path:
    """Find a run directory by hash or by matching meta.json fields."""
    if run_hash is not None:
        run_dir = results_root / artifact / f"v{schema_version}" / run_hash
        if not run_dir.exists():
            raise FileNotFoundError(f"No run dir: {run_dir}")
        return run_dir

    if meta_query is None:
        raise ValueError("Provide either run_hash or meta_query")

    candidates: List[Path] = []
    for run_dir in _iter_run_dirs(results_root, artifact, schema_version):
        try:
            meta = _load_meta(run_dir)
        except Exception:
            continue
        if _meta_matches_query(meta, meta_query):
            candidates.append(run_dir)

    if len(candidates) == 0:
        base = results_root / artifact / f"v{schema_version}"
        raise FileNotFoundError(
            f"No matching run found under {base}. "
            f"Generate the data with the scripts first."
        )
    if len(candidates) == 1:
        return candidates[0]
    return _pick_latest_run(candidates)


# =============================================================================
# Main plotting functions (artifact-based)
# =============================================================================

@overload
def plot_exact_vs_lb(
    *,
    exact_hash: str,
    lb_hash: str,
    results_root: Optional[Path] = None,
    per_site: bool = False,
    Ns: Optional[Iterable[int]] = None,
    show: bool = True,
    save_path: Optional[Path] = None,
) -> Dict[str, Any]:
    ...


@overload
def plot_exact_vs_lb(
    *,
    model: str,
    model_params: Dict[str, float],
    boundary: str = "periodic",
    lb_basis: str = "npa",
    npa_level: int = 1,
    results_root: Optional[Path] = None,
    per_site: bool = False,
    Ns: Optional[Iterable[int]] = None,
    show: bool = True,
    save_path: Optional[Path] = None,
) -> Dict[str, Any]:
    ...


def plot_exact_vs_lb(
    *,
    model: Optional[str] = None,
    model_params: Optional[Dict[str, float]] = None,
    boundary: str = "periodic",
    per_site: bool = False,
    Ns: Optional[Iterable[int]] = None,
    exact_hash: Optional[str] = None,
    lb_hash: Optional[str] = None,
    lb_basis: str = "npa",
    npa_level: int = 1,
    results_root: Optional[Path] = None,
    show: bool = True,
    save_path: Optional[Path] = None,
) -> Dict[str, Any]:
    """Plot exact energy vs moment-relaxation lower bound from saved artifacts.

    Two call styles:
      1) Hash-based: provide `exact_hash` and `lb_hash` only.
      2) Param-based: provide `model`, `model_params`, `boundary`, etc.

    Args:
        model: Model name ("ising", "heisenberg", "heisenberg_j2").
        model_params: Model parameters dict (e.g., {"J": 1.0, "h": 0.7, "k": 0.3}).
        boundary: "periodic" or "open".
        per_site: If True, plot energy per site (E/N).
        Ns: Filter to these N values only.
        exact_hash: Explicit hash for exact run.
        lb_hash: Explicit hash for LB run.
        lb_basis: Basis used for LB ("npa", "heisenberg_simple", etc.).
        npa_level: NPA level k (only meaningful when lb_basis="npa").
        results_root: Override default results directory.
        show: Whether to call plt.show().
        save_path: If provided, save figure to this path.

    Returns:
        Dict with run directories, arrays (N, E0, E_lb, gap), and figure/axes.
    """
    results_root = results_root or _default_results_root()

    if lb_basis != "npa" and npa_level != 1:
        raise ValueError("`npa_level` is only valid when lb_basis='npa'.")

    if (exact_hash is None or lb_hash is None) and (model is None or model_params is None):
        raise ValueError(
            "Provide either `exact_hash` and `lb_hash` (hash-based lookup) "
            "or `model` and `model_params` (param-based lookup)."
        )

    # --- Exact run lookup ---
    exact_query = None
    if exact_hash is None:
        assert model is not None and model_params is not None
        exact_query = {
            "artifact": "spin_exact_ground_energy",
            "schema_version": 1,
            "model": model,
            "method": "exact_diagonalization",
            "params": {k: float(v) for k, v in model_params.items()},
            "boundary": boundary,
        }
    exact_run = _find_run_dir(
        results_root=results_root,
        artifact="spin_exact_ground_energy",
        schema_version=1,
        run_hash=exact_hash,
        meta_query=exact_query,
    )

    # --- LB run lookup ---
    lb_query = None
    if lb_hash is None:
        assert model is not None and model_params is not None
        lb_query = {
            "artifact": "spin_moment_energy_lb",
            "schema_version": 1,
            "model": model,
            "method": "pauli_moment_relaxation",
            "params": {k: float(v) for k, v in model_params.items()},
            "boundary": boundary,
            "basis": lb_basis,
            "sense": "min",
        }
        if lb_basis == "npa":
            lb_query["npa_level"] = int(npa_level)
    lb_run = _find_run_dir(
        results_root=results_root,
        artifact="spin_moment_energy_lb",
        schema_version=1,
        run_hash=lb_hash,
        meta_query=lb_query,
    )

    exact_meta = _load_meta(exact_run)
    lb_meta = _load_meta(lb_run)

    # Infer model from meta if using hash-based lookup
    if model is None:
        model = str(exact_meta.get("model", lb_meta.get("model", "unknown")))
    if model_params is None:
        mp = exact_meta.get("params")
        model_params = mp if isinstance(mp, dict) else {}

    # Validate consistency
    meta_model_exact = exact_meta.get("model")
    meta_model_lb = lb_meta.get("model")
    if meta_model_exact is not None and str(meta_model_exact) != str(model):
        raise ValueError(f"Exact run model={meta_model_exact!r} does not match {model!r}")
    if meta_model_lb is not None and str(meta_model_lb) != str(model):
        raise ValueError(f"LB run model={meta_model_lb!r} does not match {model!r}")

    meta_basis = lb_meta.get("basis")
    if meta_basis is not None and str(meta_basis) != str(lb_basis):
        raise ValueError(f"LB run basis={meta_basis!r} does not match {lb_basis!r}")

    if lb_basis == "npa":
        meta_npa_level = lb_meta.get("npa_level")
        if meta_npa_level is None:
            raise ValueError(
                "LB run meta.json missing `npa_level`. "
                "Regenerate artifacts with updated scripts."
            )
        if int(meta_npa_level) != int(npa_level):
            raise ValueError(
                f"LB run npa_level={meta_npa_level} does not match {npa_level}"
            )

    # --- Load data ---
    exact_npz = _load_npz(exact_run)
    lb_npz = _load_npz(lb_run)

    N_exact = np.asarray(exact_npz["N"], dtype=int)
    E0 = np.asarray(exact_npz["E0"], dtype=float)
    N_lb = np.asarray(lb_npz["N"], dtype=int)
    E_lb = np.asarray(lb_npz["E_lb"], dtype=float)

    # Filter by Ns if provided
    if Ns is not None:
        Ns_set = set(int(n) for n in Ns)
        mask_ex = np.array([int(n) in Ns_set for n in N_exact], dtype=bool)
        mask_lb = np.array([int(n) in Ns_set for n in N_lb], dtype=bool)
        N_exact, E0 = N_exact[mask_ex], E0[mask_ex]
        N_lb, E_lb = N_lb[mask_lb], E_lb[mask_lb]

    # Sort by N
    ex_order = np.argsort(N_exact)
    lb_order = np.argsort(N_lb)
    N_exact, E0 = N_exact[ex_order], E0[ex_order]
    N_lb, E_lb = N_lb[lb_order], E_lb[lb_order]

    # Compute gap on overlap
    overlap = sorted(set(int(n) for n in N_exact).intersection(int(n) for n in N_lb))
    overlap = np.array(overlap, dtype=int)
    ex_map = {int(n): float(e) for n, e in zip(N_exact, E0)}
    lb_map = {int(n): float(e) for n, e in zip(N_lb, E_lb)}
    gap = np.array([ex_map[int(n)] - lb_map[int(n)] for n in overlap], dtype=float)

    # Prepare plot data
    if per_site:
        E0_plot = E0 / N_exact
        E_lb_plot = E_lb / N_lb
        gap_plot = gap / overlap
        ylabel_e = "Energy per site (E/N)"
        ylabel_gap = "Gap per site (Exact - LB)/N"
    else:
        E0_plot = E0
        E_lb_plot = E_lb
        gap_plot = gap
        ylabel_e = "Energy (E)"
        ylabel_gap = "Gap (Exact - LB)"

    # --- Plotting ---
    fig, axes = plt.subplots(1, 2, figsize=(14, 5))

    axes[0].plot(N_exact, E0_plot, marker="o", linewidth=2, label="Exact")
    if lb_basis == "npa":
        lb_label = f"LB ({lb_basis}, k={int(npa_level)})"
    else:
        lb_label = f"LB ({lb_basis})"
    axes[0].plot(N_lb, E_lb_plot, marker="s", linewidth=2, label=lb_label)
    axes[0].set_xlabel("Number of spins N")
    axes[0].set_ylabel(ylabel_e)
    axes[0].set_title(f"{model}: Exact vs Lower Bound")
    axes[0].grid(True, alpha=0.3)
    axes[0].legend()
    axes[0].xaxis.set_major_locator(MaxNLocator(integer=True))

    axes[1].plot(overlap, gap_plot, marker="^", color="red", linewidth=2)
    axes[1].set_xlabel("Number of spins N")
    axes[1].set_ylabel(ylabel_gap)
    axes[1].set_title("Relaxation Gap (Exact - LB)")
    axes[1].grid(True, which="both", alpha=0.3)
    axes[1].xaxis.set_major_locator(MaxNLocator(integer=True))
    if len(gap_plot) > 0 and np.all(gap_plot > 0):
        axes[1].set_yscale("log")

    plt.tight_layout()
    if save_path is not None:
        plt.savefig(save_path)
    if show:
        plt.show()

    return {
        "exact_run_dir": exact_run,
        "lb_run_dir": lb_run,
        "N_exact": N_exact,
        "E0": E0,
        "N_lb": N_lb,
        "E_lb": E_lb,
        "N_overlap": overlap,
        "gap": gap,
        "figure": fig,
        "axes": axes,
    }

def plot_heisenberg_j2_sweep(
    *,
    N: int,
    J2_values: Iterable[float],
    boundary: str = "periodic",
    per_site: bool = True,
    results_root: Optional[Path] = None,
    show: bool = True,
    save_path: Optional[Path] = None,
    print_table: bool = True,
) -> Dict[str, Any]:
    """Plot Heisenberg-J2 ground state energy vs J2.

    Loads artifacts for a fixed N and multiple J2 values, comparing
    exact diagonalization with SDP lower bounds.

    NOTE: Each J2 value requires separate artifact runs with model="heisenberg_j2"
    and J2 specified in model_params.

    Args:
        N: System size.
        J2_values: J2 coupling values to plot.
        boundary: "periodic" or "open".
        per_site: If True, plot E/N.
        results_root: Override default results directory.
        show: Whether to call plt.show().
        save_path: If provided, save figure to this path.
        print_table: If True, print a summary table.

    Returns:
        Dict with J2 values, energies, and figure.
    """
    results_root = results_root or _default_results_root()
    J2_list = list(J2_values)

    exact_energies = []
    sdp_lbs = []
    bases_used = []

    for J2 in J2_list:
        model_params = {"J2": float(J2)}

        # Choose basis based on J2 regime
        lb_basis = "heisenberg_j2_weak" if J2 <= 1.0 else "heisenberg_j2_strong"
        bases_used.append(lb_basis)

        # Find exact run
        exact_query = {
            "artifact": "spin_exact_ground_energy",
            "schema_version": 1,
            "model": "heisenberg_j2",
            "method": "exact_diagonalization",
            "params": model_params,
            "boundary": boundary,
        }
        try:
            exact_run = _find_run_dir(
                results_root=results_root,
                artifact="spin_exact_ground_energy",
                schema_version=1,
                meta_query=exact_query,
            )
            exact_npz = _load_npz(exact_run)
            N_arr = np.asarray(exact_npz["N"], dtype=int)
            E0_arr = np.asarray(exact_npz["E0"], dtype=float)
            idx = np.where(N_arr == N)[0]
            if len(idx) == 0:
                raise FileNotFoundError(f"No N={N} in exact run for J2={J2}")
            exact_energies.append(float(E0_arr[idx[0]]))
        except FileNotFoundError as e:
            raise FileNotFoundError(
                f"Missing exact run for heisenberg_j2 with J2={J2}. "
                f"Generate it first. Original: {e}"
            )

        # Find LB run
        lb_query = {
            "artifact": "spin_moment_energy_lb",
            "schema_version": 1,
            "model": "heisenberg_j2",
            "method": "pauli_moment_relaxation",
            "params": model_params,
            "boundary": boundary,
            "basis": lb_basis,
            "sense": "min",
        }
        try:
            lb_run = _find_run_dir(
                results_root=results_root,
                artifact="spin_moment_energy_lb",
                schema_version=1,
                meta_query=lb_query,
            )
            lb_npz = _load_npz(lb_run)
            N_arr_lb = np.asarray(lb_npz["N"], dtype=int)
            E_lb_arr = np.asarray(lb_npz["E_lb"], dtype=float)
            idx = np.where(N_arr_lb == N)[0]
            if len(idx) == 0:
                raise FileNotFoundError(f"No N={N} in LB run for J2={J2}")
            sdp_lbs.append(float(E_lb_arr[idx[0]]))
        except FileNotFoundError as e:
            raise FileNotFoundError(
                f"Missing LB run for heisenberg_j2 with J2={J2}, basis={lb_basis}. "
                f"Generate it first. Original: {e}"
            )

    J2_arr = np.array(J2_list, dtype=float)
    exact_arr = np.array(exact_energies, dtype=float)
    lb_arr = np.array(sdp_lbs, dtype=float)
    gap = exact_arr - lb_arr

    # Prepare plot data
    if per_site:
        exact_plot = exact_arr / N
        lb_plot = lb_arr / N
        gap_plot = gap / N
        ylabel = "Energy per site (E/N)"
        ylabel_gap = "Gap per site (Exact - LB)/N"
    else:
        exact_plot = exact_arr
        lb_plot = lb_arr
        gap_plot = gap
        ylabel = "Energy (E)"
        ylabel_gap = "Gap (Exact - LB)"

    # --- Plotting ---
    fig, axes = plt.subplots(1, 2, figsize=(14, 5))

    axes[0].plot(J2_arr, exact_plot, marker="o", linewidth=2, markersize=8, label="Exact")
    axes[0].plot(J2_arr, lb_plot, marker="s", linewidth=2, markersize=8, label="SDP LB")
    axes[0].axvline(x=1.0, color="gray", linestyle="--", alpha=0.5, label="J₂=1 (regime change)")
    axes[0].set_xlabel("Second-neighbor coupling $J_2$")
    axes[0].set_ylabel(ylabel)
    axes[0].set_title(f"Heisenberg-J₂ Chain: Exact vs SDP (N={N})")
    axes[0].grid(True, alpha=0.3)
    axes[0].legend()

    axes[1].plot(J2_arr, gap_plot, marker="^", color="red", linewidth=2, markersize=8)
    axes[1].axvline(x=1.0, color="gray", linestyle="--", alpha=0.5)
    axes[1].set_xlabel("Second-neighbor coupling $J_2$")
    axes[1].set_ylabel(ylabel_gap)
    axes[1].set_title("Relaxation Gap")
    axes[1].grid(True, alpha=0.3)

    plt.tight_layout()
    if save_path is not None:
        plt.savefig(save_path)
    if show:
        plt.show()

    if print_table:
        print("=" * 100)
        print(f"Heisenberg-J₂ Chain (N={N}) - Exact vs SDP Comparison")
        print("=" * 100)
        print(f"{'J2':<10} {'Exact E':<15} {'SDP LB':<15} {'Gap':<15} {'Gap/N':<15} {'Basis':<20}")
        print("-" * 100)
        for i, J2 in enumerate(J2_list):
            print(
                f"{J2:<10.3f} {exact_arr[i]:<15.8f} {lb_arr[i]:<15.8f} "
                f"{gap[i]:<15.8e} {gap[i]/N:<15.8e} {bases_used[i]:<20}"
            )
        print("=" * 100)

    return {
        "N": N,
        "J2": J2_arr,
        "exact_energies": exact_arr,
        "sdp_lbs": lb_arr,
        "gap": gap,
        "bases_used": bases_used,
        "figure": fig,
        "axes": axes,
    }


def plot_runtime_comparison(
    *,
    model: str = "ising",
    model_params: Optional[Dict[str, float]] = None,
    boundary: str = "periodic",
    lb_basis: str = "npa",
    npa_levels: Iterable[int] = (1, 2),
    use: str = "t_avg",
    logy: bool = True,
    Ns: Optional[Iterable[int]] = None,
    results_root: Optional[Path] = None,
    show: bool = True,
    save_path: Optional[Path] = None,
) -> Dict[str, Any]:
    """Compare runtime of exact diagonalization vs SDP relaxation.

    Loads timing data from saved artifacts.

    Args:
        model: Model name.
        model_params: Model parameters.
        boundary: "periodic" or "open".
        lb_basis: Basis for LB.
        npa_levels: NPA levels to compare.
        use: "t_avg" or "t_best".
        logy: Log scale for y-axis.
        Ns: Filter to these N values only.
        results_root: Override default results directory.
        show: Whether to call plt.show().
        save_path: If provided, save figure to this path.

    Returns:
        Dict with timing data and figure.
    """
    results_root = results_root or _default_results_root()
    model_params = model_params or {}
    npa_levels = list(npa_levels)

    # --- Load exact timing data ---
    exact_query = {
        "artifact": "spin_exact_ground_energy",
        "schema_version": 1,
        "model": model,
        "method": "exact_diagonalization",
        "params": {k: float(v) for k, v in model_params.items()},
        "boundary": boundary,
    }
    exact_run = _find_run_dir(
        results_root=results_root,
        artifact="spin_exact_ground_energy",
        schema_version=1,
        meta_query=exact_query,
    )
    exact_npz = _load_npz(exact_run)
    N_exact = np.asarray(exact_npz["N"], dtype=int)
    t_exact = np.asarray(exact_npz.get(use, exact_npz.get("t_avg", np.zeros_like(N_exact))), dtype=float)

    order = np.argsort(N_exact)
    N_exact, t_exact = N_exact[order], t_exact[order]

    Ns_set = None
    if Ns is not None:
        Ns_set = set(int(n) for n in Ns)
        mask = np.array([int(n) in Ns_set for n in N_exact], dtype=bool)
        N_exact, t_exact = N_exact[mask], t_exact[mask]

    # --- Load LB timing data for each level ---
    npa_data: Dict[int, Dict[str, np.ndarray]] = {}
    for lvl in npa_levels:
        lb_query = {
            "artifact": "spin_moment_energy_lb",
            "schema_version": 1,
            "model": model,
            "method": "pauli_moment_relaxation",
            "params": {k: float(v) for k, v in model_params.items()},
            "boundary": boundary,
            "basis": lb_basis,
            "sense": "min",
        }
        if lb_basis == "npa":
            lb_query["npa_level"] = int(lvl)

        lb_run = _find_run_dir(
            results_root=results_root,
            artifact="spin_moment_energy_lb",
            schema_version=1,
            meta_query=lb_query,
        )
        lb_npz = _load_npz(lb_run)
        N_lb = np.asarray(lb_npz["N"], dtype=int)
        t_lb = np.asarray(lb_npz.get(use, lb_npz.get("t_avg", np.zeros_like(N_lb))), dtype=float)

        order = np.argsort(N_lb)
        N_lb, t_lb = N_lb[order], t_lb[order]

        if Ns_set is not None:
            mask = np.array([int(n) in Ns_set for n in N_lb], dtype=bool)
            N_lb, t_lb = N_lb[mask], t_lb[mask]

        npa_data[lvl] = {"N": N_lb, "t": t_lb}

    # --- Plotting ---
    fig, ax = plt.subplots(figsize=(10, 6))

    ax.plot(N_exact, t_exact, marker="o", linewidth=2, label=f"Exact ({use})")
    for lvl in npa_levels:
        d = npa_data[lvl]
        label = f"SDP (k={lvl})" if lb_basis == "npa" else f"SDP ({lb_basis})"
        ax.plot(d["N"], d["t"], marker="s", linewidth=2, label=f"{label} ({use})")

    ax.set_xlabel("Number of spins N")
    ax.set_ylabel("Runtime (seconds)")
    ax.set_title(f"{model}: Runtime Comparison")
    ax.xaxis.set_major_locator(MaxNLocator(integer=True))
    if logy:
        ax.set_yscale("log")
    ax.grid(True, alpha=0.3)
    ax.legend()

    plt.tight_layout()
    if save_path is not None:
        plt.savefig(save_path)
    if show:
        plt.show()

    return {
        "exact": {"N": N_exact, "t": t_exact},
        "npa": npa_data,
        "figure": fig,
        "axes": ax,
    }


# =============================================================================
# Utility / exploratory plots (compute on the fly - no artifacts needed)
# =============================================================================

def npa_basis_size_heatmap(
    N_max: int,
    npa_level_max: int,
    *,
    show: bool = True,
    save_path: Optional[Path] = None,
) -> np.ndarray:
    """Generate a heatmap of NPA basis sizes for varying N and NPA level.

    This computes basis sizes on the fly (fast for small N/levels).

    Args:
        N_max: Maximum number of spins.
        npa_level_max: Maximum NPA level.
        show: Whether to call plt.show().
        save_path: If provided, save figure to this path.

    Returns:
        2D array of basis sizes: sizes[level_idx, N_idx].
    """
    N_values = np.arange(1, N_max + 1)
    levels = np.arange(1, npa_level_max + 1)

    sizes = np.array(
        [[len(generate_npa_basis(N=N, k=lvl).words) for N in N_values] for lvl in levels],
        dtype=int,
    )

    fig, ax = plt.subplots(figsize=(10, 6))
    im = ax.imshow(sizes, origin="lower", aspect="auto", cmap="viridis")

    cbar = plt.colorbar(im, ax=ax)
    cbar.set_label("NPA basis size")

    ax.set_xticks(np.arange(len(N_values)))
    ax.set_xticklabels(N_values)
    ax.set_yticks(np.arange(len(levels)))
    ax.set_yticklabels(levels)
    ax.set_xlabel("Number of spins N")
    ax.set_ylabel("NPA level k")
    ax.set_title("NPA Basis Size vs N and Level")

    # Annotate cells
    threshold = sizes.max() / 2
    for yi, lvl in enumerate(levels):
        for xi, N in enumerate(N_values):
            val = sizes[yi, xi]
            color = "white" if val > threshold else "black"
            ax.text(xi, yi, str(val), ha="center", va="center", color=color, fontsize=8)

    plt.tight_layout()
    if save_path is not None:
        plt.savefig(save_path)
    if show:
        plt.show()

    return sizes


def plot_basis_size_comparison(
    N_values: Iterable[int],
    *,
    npa_levels: Iterable[int] = (1, 2, 3),
    include_paper_basis: bool = True,
    logy: bool = True,
    show: bool = True,
    save_path: Optional[Path] = None,
) -> Dict[str, np.ndarray]:
    """Compare basis sizes of different NPA levels and the Heisenberg paper basis.

    This computes basis sizes on the fly.

    Args:
        N_values: System sizes to compare.
        npa_levels: NPA levels to include.
        include_paper_basis: Whether to include the Heisenberg paper basis.
        logy: Use log scale for y-axis.
        show: Whether to call plt.show().
        save_path: If provided, save figure to this path.

    Returns:
        Dict with N and basis sizes for each method.
    """
    Ns = np.array(list(N_values), dtype=int)
    npa_levels = list(npa_levels)
    result: Dict[str, np.ndarray] = {"N": Ns}

    for lvl in npa_levels:
        sizes = np.array([len(generate_npa_basis(N=N, k=lvl).words) for N in Ns])
        result[f"npa_k{lvl}"] = sizes

    if include_paper_basis:
        paper_sizes = np.array([len(generate_heisenberg_paper_basis(N=N)) for N in Ns])
        result["heisenberg_paper"] = paper_sizes

    # Plot
    fig, ax = plt.subplots(figsize=(10, 6))

    for lvl in npa_levels:
        ax.plot(Ns, result[f"npa_k{lvl}"], marker="o", linewidth=2, label=f"NPA k={lvl}")

    if include_paper_basis:
        ax.plot(Ns, result["heisenberg_paper"], marker="s", linewidth=2, linestyle="--", label="Heisenberg paper")

    if logy:
        ax.set_yscale("log")

    ax.set_xlabel("Number of spins N")
    ax.set_ylabel("Basis size")
    ax.xaxis.set_major_locator(MaxNLocator(integer=True))
    ax.set_title("Basis Size Comparison")
    ax.grid(True, which="both", alpha=0.3)
    ax.legend()

    plt.tight_layout()
    if save_path is not None:
        plt.savefig(save_path)
    if show:
        plt.show()

    return result


# =============================================================================
# Optimization Sweep Plotting Functions
# =============================================================================

def _find_optimization_run_dir(
    *,
    results_root: Path,
    run_hash: Optional[str] = None,
    meta_query: Optional[Dict[str, Any]] = None,
) -> Path:
    """Find an optimization sweep run directory."""
    return _find_run_dir(
        results_root=results_root,
        artifact="spin_optimization_sweep",
        schema_version=1,
        run_hash=run_hash,
        meta_query=meta_query,
    )


def _load_optimization_data(run_dir: Path) -> Tuple[Dict[str, Any], Dict[str, np.ndarray]]:
    """Load optimization sweep meta and data."""
    meta = _load_meta(run_dir)
    data = _load_npz(run_dir)
    return meta, data


def _compute_exact_ground_energy(
    model: str,
    N: int,
    boundary: str,
    model_params: Dict[str, float],
) -> float:
    """Compute exact ground state energy for a model."""
    from spins_sdp import models
    
    if model == "ising":
        H = models.ising_hamiltonian_exact(N, boundary=boundary, **model_params)
    elif model == "heisenberg":
        H = models.heisenberg_hamiltonian_exact(N, boundary=boundary)
    elif model == "heisenberg_j2":
        H = models.heisenberg_j2_hamiltonian_exact(N, boundary=boundary, **model_params)
    else:
        raise ValueError(f"Unknown model: {model}")
    
    eigenvalues = H.eigenenergies(eigvals=1)
    return float(np.asarray(eigenvalues)[0])


def _compute_full_relaxation_lower_bound(
    *,
    model: str,
    N: int,
    boundary: str,
    model_params: Dict[str, float],
    end_level: int,
    solver: str,
    mosek_tol: float,
) -> float:
    """Compute the SDP lower bound for the full relaxation (end_level basis).

    This is used by convergence plots when the sweep did not include k=L.
    """
    from spins_sdp import models
    from spins_sdp.sdp import solve_pauli_relaxation

    if model == "ising":
        H = models.ising_hamiltonian_dict(N=N, boundary=boundary, **model_params)
    elif model == "heisenberg":
        H = models.heisenberg_hamiltonian_dict(N=N, boundary=boundary)
    elif model == "heisenberg_j2":
        H = models.heisenberg_j2_hamiltonian_dict(N=N, boundary=boundary, **model_params)
    else:
        raise ValueError(f"Unknown model: {model}")

    full_basis = generate_npa_basis(N=N, k=int(end_level)).words
    lb = solve_pauli_relaxation(
        full_basis,
        H,
        sense="min",
        solver=solver,
        mosek_tol=float(mosek_tol),
        verbose=False,
    )
    return float(lb)


def _get_exact_energy_from_artifact_or_compute(
    model: str,
    N: int,
    boundary: str,
    model_params: Dict[str, float],
    results_root: Path,
) -> Tuple[float, str]:
    """Try to load exact energy from artifact, otherwise compute it.
    
    Returns:
        (energy, source) where source is "artifact" or "computed"
    """
    try:
        exact_query = {
            "artifact": "spin_exact_ground_energy",
            "schema_version": 1,
            "model": model,
            "boundary": boundary,
        }
        if model_params:
            exact_query["params"] = {k: float(v) for k, v in model_params.items()}
        
        exact_run = _find_run_dir(
            results_root=results_root,
            artifact="spin_exact_ground_energy",
            schema_version=1,
            meta_query=exact_query,
        )
        
        exact_npz = _load_npz(exact_run)
        N_arr = np.asarray(exact_npz["N"], dtype=int)
        E0_arr = np.asarray(exact_npz["E0"], dtype=float)
        
        # Find the matching N
        idx = np.where(N_arr == N)[0]
        if len(idx) > 0:
            return float(E0_arr[idx[0]]), "artifact"
    except FileNotFoundError:
        pass
    
    # Fall back to computing
    E0 = _compute_exact_ground_energy(model, N, boundary, model_params)
    return E0, "computed"


def plot_optimization_sweep(
    *,
    run_hash: Optional[str] = None,
    model: Optional[str] = None,
    N: Optional[int] = None,
    boundary: str = "periodic",
    model_params: Optional[Dict[str, float]] = None,
    start_level: int = 1,
    end_level: int = 2,
    method: str = "sa",
    exact_energy: Optional[float] = None,
    results_root: Optional[Path] = None,
    show_seeds: bool = False,
    per_site: bool = False,
    show: bool = True,
    save_path: Optional[Path] = None,
) -> Dict[str, Any]:
    """Plot best lower bound vs number of added monomials (k) for an optimization sweep.
    
    This is the main plotting function for optimization results. It shows how the
    SDP lower bound improves as more monomials are added to the basis.
    
    Args:
        run_hash: Explicit hash of the optimization run directory.
        model: Model name ("ising", "heisenberg", "heisenberg_j2").
        N: Number of sites.
        boundary: "periodic" or "open".
        model_params: Model-specific parameters (e.g., {"J2": 0.5}).
        start_level: NPA level for starting set.
        end_level: NPA level for final set.
        method: Optimization method ("sa" or "pt").
        exact_energy: Exact ground state energy. If None, will try to load from
                     artifact or compute it.
        results_root: Override default results directory.
        show_seeds: If True, show individual seed results as scatter points.
        per_site: If True, plot energy per site.
        show: Whether to call plt.show().
        save_path: If provided, save figure to this path.
    
    Returns:
        Dict with run info, data arrays, exact energy, and figure/axes.
    
    Example:
        # By hash
        plot_optimization_sweep(run_hash="270b29da020d10b0")
        
        # By parameters
        plot_optimization_sweep(
            model="heisenberg",
            N=4,
            boundary="periodic",
            start_level=1,
            end_level=2,
            method="sa",
        )
    """
    results_root = results_root or _default_results_root()
    
    # Build query if not using hash
    meta_query = None
    if run_hash is None:
        if model is None or N is None:
            raise ValueError("Provide either run_hash or (model, N)")
        meta_query = {
            "artifact": "spin_optimization_sweep",
            "schema_version": 1,
            "model": model,
            "N": int(N),
            "boundary": boundary,
            "start_level": int(start_level),
            "end_level": int(end_level),
            "method": method,
        }
        if model_params:
            meta_query["model_params"] = {k: float(v) for k, v in model_params.items()}
    
    # Find and load run
    run_dir = _find_optimization_run_dir(
        results_root=results_root,
        run_hash=run_hash,
        meta_query=meta_query,
    )
    
    meta, data = _load_optimization_data(run_dir)
    
    # Extract info from meta
    model = meta.get("model", model)
    N = meta.get("N", N)
    boundary = meta.get("boundary", boundary)
    model_params = meta.get("model_params", model_params or {})
    L = meta.get("L", meta.get("adding_set_size"))
    starting_set_size = meta.get("starting_set_size", 0)
    
    # Get exact energy
    E0_source = "provided"
    if exact_energy is None:
        exact_energy, E0_source = _get_exact_energy_from_artifact_or_compute(
            model=model,
            N=N,
            boundary=boundary,
            model_params=model_params,
            results_root=results_root,
        )
    
    # Extract data arrays
    k_arr = data["k"]
    best_value_arr = data["best_value"]
    seed_arr = data.get("seed", np.zeros_like(k_arr))
    
    # Compute best value per k (across all seeds)
    unique_ks = np.unique(k_arr)
    best_per_k = {}
    all_per_k = {}
    
    for k in unique_ks:
        mask = k_arr == k
        values = best_value_arr[mask]
        best_per_k[int(k)] = float(np.max(values))
        all_per_k[int(k)] = values
    
    ks_sorted = np.array(sorted(best_per_k.keys()))
    best_vals = np.array([best_per_k[k] for k in ks_sorted])
    
    # Total basis size at each k
    total_basis_size = starting_set_size + ks_sorted
    
    # Prepare plot values
    if per_site:
        E0_plot = exact_energy / N
        best_vals_plot = best_vals / N
        ylabel = "Energy per site (E/N)"
    else:
        E0_plot = exact_energy
        best_vals_plot = best_vals
        ylabel = "Energy"
    
    # --- Plotting ---
    fig, axes = plt.subplots(1, 2, figsize=(14, 5))
    
    # Left plot: Lower bound vs k
    ax1 = axes[0]
    
    # Plot best per k
    ax1.plot(ks_sorted, best_vals_plot, marker="o", linewidth=2, markersize=6,
             label="Best LB (optimization)", color="C0", zorder=3)
    
    # Optionally show all seeds
    if show_seeds:
        for k in unique_ks:
            values = all_per_k[int(k)]
            if per_site:
                values = values / N
            ax1.scatter([k] * len(values), values, alpha=0.3, s=20, color="C0", zorder=2)
    
    # Plot exact energy as horizontal line
    ax1.axhline(E0_plot, color="red", linestyle="--", linewidth=2, 
                label=f"Exact $E_0$ ({E0_source})", zorder=1)
    
    ax1.set_xlabel("Number of added monomials (k)")
    ax1.set_ylabel(ylabel)
    ax1.set_title(f"{model.capitalize()} N={N}: Lower Bound vs Added Monomials")
    ax1.xaxis.set_major_locator(MaxNLocator(integer=True))
    ax1.grid(True, alpha=0.3)
    ax1.legend(loc="lower right")
    
    # Right plot: Gap (E0 - LB) vs k
    ax2 = axes[1]
    
    gap = exact_energy - best_vals
    if per_site:
        gap_plot = gap / N
        gap_ylabel = "Gap per site ($E_0$ - LB)/N"
    else:
        gap_plot = gap
        gap_ylabel = "Gap ($E_0$ - LB)"
    
    ax2.plot(ks_sorted, gap_plot, marker="^", linewidth=2, markersize=6, color="green")
    ax2.axhline(0, color="gray", linestyle=":", linewidth=1)
    ax2.set_xlabel("Number of added monomials (k)")
    ax2.set_ylabel(gap_ylabel)
    ax2.set_title("Relaxation Gap")
    ax2.xaxis.set_major_locator(MaxNLocator(integer=True))
    ax2.grid(True, alpha=0.3)
    
    # Use log scale if all gaps are positive
    if len(gap_plot) > 0 and np.all(gap_plot > 0):
        ax2.set_yscale("log")
    
    plt.tight_layout()
    
    if save_path is not None:
        plt.savefig(save_path)
    if show:
        plt.show()
    
    return {
        "run_dir": run_dir,
        "meta": meta,
        "k": ks_sorted,
        "best_values": best_vals,
        "exact_energy": exact_energy,
        "exact_energy_source": E0_source,
        "gap": gap,
        "L": L,
        "starting_set_size": starting_set_size,
        "figure": fig,
        "axes": axes,
    }


def plot_optimization_convergence(
    *,
    run_hash: Optional[str] = None,
    model: Optional[str] = None,
    N: Optional[int] = None,
    boundary: str = "periodic",
    model_params: Optional[Dict[str, float]] = None,
    start_level: int = 1,
    end_level: int = 2,
    method: str = "sa",
    exact_energy: Optional[float] = None,
    full_relaxation_energy: Optional[float] = None,
    results_root: Optional[Path] = None,
    show: bool = True,
    save_path: Optional[Path] = None,
) -> Dict[str, Any]:
    """Plot optimization convergence: best LB vs fraction of monomials used.
    
    Shows how quickly the lower bound approaches the full relaxation value
    as we add more monomials. Useful for understanding if a small subset
    of monomials can achieve most of the improvement.
    
    Args:
        run_hash: Explicit hash of the optimization run.
        model, N, boundary, model_params: Model specification for lookup.
        start_level, end_level: NPA levels for basis.
        method: Optimization method.
        exact_energy: Exact ground state energy (optional).
        full_relaxation_energy: Energy with all monomials (k=L). If None,
                               will try to extract from data.
        results_root: Override default results directory.
        show: Whether to call plt.show().
        save_path: If provided, save figure.
    
    Returns:
        Dict with convergence data and figure.
    """
    results_root = results_root or _default_results_root()
    
    # Build query
    meta_query = None
    if run_hash is None:
        if model is None or N is None:
            raise ValueError("Provide either run_hash or (model, N)")
        meta_query = {
            "artifact": "spin_optimization_sweep",
            "model": model,
            "N": int(N),
            "boundary": boundary,
            "start_level": int(start_level),
            "end_level": int(end_level),
            "method": method,
        }
        if model_params:
            meta_query["model_params"] = {k: float(v) for k, v in model_params.items()}
    
    run_dir = _find_optimization_run_dir(
        results_root=results_root,
        run_hash=run_hash,
        meta_query=meta_query,
    )
    
    meta, data = _load_optimization_data(run_dir)
    
    model = meta.get("model", model)
    N = meta.get("N", N)
    boundary = meta.get("boundary", boundary)
    model_params = meta.get("model_params", model_params or {})
    end_level = int(meta.get("end_level", end_level))
    L = meta.get("L", meta.get("adding_set_size"))
    starting_set_size = meta.get("starting_set_size", 0)
    
    # Get exact energy
    if exact_energy is None:
        exact_energy, _ = _get_exact_energy_from_artifact_or_compute(
            model=model, N=N, boundary=boundary,
            model_params=model_params, results_root=results_root,
        )
    
    # Extract data
    k_arr = data["k"]
    best_value_arr = data["best_value"]
    
    # Compute best per k
    unique_ks = np.unique(k_arr)
    best_per_k = {int(k): float(np.max(best_value_arr[k_arr == k])) for k in unique_ks}
    
    ks_sorted = np.array(sorted(best_per_k.keys()))
    best_vals = np.array([best_per_k[k] for k in ks_sorted])
    
    # Get full relaxation energy (k=L). If the sweep didn't include k=L,
    # compute the true full relaxation LB directly.
    full_relaxation_label = "Full relaxation (k=L)"
    if full_relaxation_energy is None:
        if L in best_per_k:
            full_relaxation_energy = best_per_k[L]
            full_relaxation_label = "Full relaxation (k=L)"
        else:
            try:
                full_relaxation_energy = _compute_full_relaxation_lower_bound(
                    model=model,
                    N=int(N),
                    boundary=boundary,
                    model_params=model_params,
                    end_level=end_level,
                    solver=str(meta.get("solver", "MOSEK")),
                    mosek_tol=float(meta.get("mosek_tol", 1e-9)),
                )
                full_relaxation_label = "Full relaxation (k=L)"
            except Exception:
                full_relaxation_energy = best_vals[-1]
                full_relaxation_label = f"Best available (k={int(ks_sorted[-1])})"
    
    # Starting energy (k=0)
    starting_energy = best_per_k.get(0, best_vals[0])
    
    # Fraction of monomials
    fraction = ks_sorted / L if L > 0 else ks_sorted
    
    # Normalized improvement: 0 at k=0, 1 at k=L
    total_improvement = full_relaxation_energy - starting_energy
    if abs(total_improvement) > 1e-12:
        normalized = (best_vals - starting_energy) / total_improvement
    else:
        normalized = np.zeros_like(best_vals)
    
    # --- Plotting ---
    fig, axes = plt.subplots(1, 2, figsize=(14, 5))
    
    # Left: Raw values vs fraction
    ax1 = axes[0]
    ax1.plot(fraction * 100, best_vals, marker="o", linewidth=2, label="Best LB")
    ax1.axhline(exact_energy, color="red", linestyle="--", linewidth=2, label="Exact $E_0$")
    ax1.axhline(
        full_relaxation_energy,
        color="green",
        linestyle=":",
        linewidth=2,
        label=full_relaxation_label,
    )
    ax1.set_xlabel("Fraction of monomials added (%)")
    ax1.set_ylabel("Energy")
    ax1.set_title(f"{model.capitalize()} N={N}: Convergence")
    ax1.grid(True, alpha=0.3)
    ax1.legend()
    
    # Right: Normalized improvement
    ax2 = axes[1]
    ax2.plot(fraction * 100, normalized * 100, marker="o", linewidth=2, color="purple")
    ax2.axhline(100, color="green", linestyle=":", linewidth=1)
    ax2.set_xlabel("Fraction of monomials added (%)")
    ax2.set_ylabel("% of total improvement achieved")
    ax2.set_title("Relative Improvement")
    ax2.set_ylim(-5, 105)
    ax2.grid(True, alpha=0.3)
    
    plt.tight_layout()
    
    if save_path is not None:
        plt.savefig(save_path)
    if show:
        plt.show()
    
    return {
        "run_dir": run_dir,
        "k": ks_sorted,
        "fraction": fraction,
        "best_values": best_vals,
        "normalized_improvement": normalized,
        "exact_energy": exact_energy,
        "full_relaxation_energy": full_relaxation_energy,
        "starting_energy": starting_energy,
        "L": L,
        "figure": fig,
        "axes": axes,
    }


def plot_optimization_seeds_comparison(
    *,
    run_hash: Optional[str] = None,
    model: Optional[str] = None,
    N: Optional[int] = None,
    boundary: str = "periodic",
    model_params: Optional[Dict[str, float]] = None,
    start_level: int = 1,
    end_level: int = 2,
    method: str = "sa",
    results_root: Optional[Path] = None,
    show: bool = True,
    save_path: Optional[Path] = None,
) -> Dict[str, Any]:
    """Plot comparison of results across different random seeds.
    
    Shows the variability in optimization results for each k value,
    helping understand whether more seeds are needed for reliable results.
    
    Args:
        Same as plot_optimization_sweep.
    
    Returns:
        Dict with statistics and figure.
    """
    results_root = results_root or _default_results_root()
    
    meta_query = None
    if run_hash is None:
        if model is None or N is None:
            raise ValueError("Provide either run_hash or (model, N)")
        meta_query = {
            "artifact": "spin_optimization_sweep",
            "model": model,
            "N": int(N),
            "boundary": boundary,
            "start_level": int(start_level),
            "end_level": int(end_level),
            "method": method,
        }
        if model_params:
            meta_query["model_params"] = {k: float(v) for k, v in model_params.items()}
    
    run_dir = _find_optimization_run_dir(
        results_root=results_root,
        run_hash=run_hash,
        meta_query=meta_query,
    )
    
    meta, data = _load_optimization_data(run_dir)
    
    model = meta.get("model", model)
    N = meta.get("N", N)
    
    k_arr = data["k"]
    best_value_arr = data["best_value"]
    seed_arr = data.get("seed", np.zeros_like(k_arr))
    
    # Compute statistics per k
    unique_ks = np.unique(k_arr)
    stats = {}
    
    for k in unique_ks:
        mask = k_arr == k
        values = best_value_arr[mask]
        seeds = seed_arr[mask]
        
        stats[int(k)] = {
            "min": float(np.min(values)),
            "max": float(np.max(values)),
            "mean": float(np.mean(values)),
            "std": float(np.std(values)),
            "range": float(np.max(values) - np.min(values)),
            "n_seeds": len(values),
            "values": values,
            "seeds": seeds,
        }
    
    ks_sorted = np.array(sorted(stats.keys()))
    means = np.array([stats[k]["mean"] for k in ks_sorted])
    stds = np.array([stats[k]["std"] for k in ks_sorted])
    mins = np.array([stats[k]["min"] for k in ks_sorted])
    maxs = np.array([stats[k]["max"] for k in ks_sorted])
    
    # --- Plotting ---
    fig, axes = plt.subplots(1, 2, figsize=(14, 5))
    
    # Left: Mean ± std with min/max range
    ax1 = axes[0]
    ax1.fill_between(ks_sorted, mins, maxs, alpha=0.2, color="C0", label="Min-Max range")
    ax1.fill_between(ks_sorted, means - stds, means + stds, alpha=0.4, color="C0", label="Mean ± std")
    ax1.plot(ks_sorted, means, marker="o", linewidth=2, color="C0", label="Mean")
    ax1.plot(ks_sorted, mins, marker="v", linewidth=1, linestyle=":", color="C0", alpha=0.7)
    ax1.plot(ks_sorted, maxs, marker="^", linewidth=1, linestyle=":", color="C0", alpha=0.7)
    
    ax1.set_xlabel("Number of added monomials (k)")
    ax1.set_ylabel("Energy")
    ax1.set_title(f"{model.capitalize()} N={N}: Seed Variability")
    ax1.xaxis.set_major_locator(MaxNLocator(integer=True))
    ax1.grid(True, alpha=0.3)
    ax1.legend()
    
    # Right: Standard deviation vs k
    ax2 = axes[1]
    ax2.bar(ks_sorted, stds, color="C1", alpha=0.7, edgecolor="C1")
    ax2.set_xlabel("Number of added monomials (k)")
    ax2.set_ylabel("Standard deviation across seeds")
    ax2.set_title("Optimization Variability")
    ax2.xaxis.set_major_locator(MaxNLocator(integer=True))
    ax2.grid(True, alpha=0.3, axis="y")
    
    plt.tight_layout()
    
    if save_path is not None:
        plt.savefig(save_path)
    if show:
        plt.show()
    
    return {
        "run_dir": run_dir,
        "k": ks_sorted,
        "stats": stats,
        "means": means,
        "stds": stds,
        "mins": mins,
        "maxs": maxs,
        "figure": fig,
        "axes": axes,
    }


def plot_optimization_timing(
    *,
    run_hash: Optional[str] = None,
    model: Optional[str] = None,
    N: Optional[int] = None,
    boundary: str = "periodic",
    model_params: Optional[Dict[str, float]] = None,
    start_level: int = 1,
    end_level: int = 2,
    method: str = "sa",
    results_root: Optional[Path] = None,
    show: bool = True,
    save_path: Optional[Path] = None,
) -> Dict[str, Any]:
    """Plot timing information for optimization runs.
    
    Shows how long each optimization takes vs k, useful for planning
    larger sweeps.
    
    Args:
        Same as plot_optimization_sweep.
    
    Returns:
        Dict with timing data and figure.
    """
    results_root = results_root or _default_results_root()
    
    meta_query = None
    if run_hash is None:
        if model is None or N is None:
            raise ValueError("Provide either run_hash or (model, N)")
        meta_query = {
            "artifact": "spin_optimization_sweep",
            "model": model,
            "N": int(N),
            "boundary": boundary,
            "start_level": int(start_level),
            "end_level": int(end_level),
            "method": method,
        }
        if model_params:
            meta_query["model_params"] = {k: float(v) for k, v in model_params.items()}
    
    run_dir = _find_optimization_run_dir(
        results_root=results_root,
        run_hash=run_hash,
        meta_query=meta_query,
    )
    
    meta, data = _load_optimization_data(run_dir)
    
    model = meta.get("model", model)
    N = meta.get("N", N)
    method = meta.get("method", method)
    
    k_arr = data["k"]
    elapsed_arr = data["elapsed_s"]
    n_evals_arr = data.get("n_obj_evals", np.ones_like(k_arr))
    
    # Average timing per k
    unique_ks = np.unique(k_arr)
    avg_time = {int(k): float(np.mean(elapsed_arr[k_arr == k])) for k in unique_ks}
    avg_evals = {int(k): float(np.mean(n_evals_arr[k_arr == k])) for k in unique_ks}
    
    ks_sorted = np.array(sorted(avg_time.keys()))
    times = np.array([avg_time[k] for k in ks_sorted])
    evals = np.array([avg_evals[k] for k in ks_sorted])
    
    # Time per evaluation
    time_per_eval = times / evals
    
    # --- Plotting ---
    fig, axes = plt.subplots(1, 2, figsize=(14, 5))
    
    # Left: Total time per k
    ax1 = axes[0]
    ax1.bar(ks_sorted, times, color="C2", alpha=0.7, edgecolor="C2")
    ax1.set_xlabel("Number of added monomials (k)")
    ax1.set_ylabel("Average time per run (seconds)")
    ax1.set_title(f"{model.capitalize()} N={N}, method={method}: Timing")
    ax1.xaxis.set_major_locator(MaxNLocator(integer=True))
    ax1.grid(True, alpha=0.3, axis="y")
    
    # Right: Time per objective evaluation
    ax2 = axes[1]
    ax2.plot(ks_sorted, time_per_eval * 1000, marker="o", linewidth=2, color="C3")
    ax2.set_xlabel("Number of added monomials (k)")
    ax2.set_ylabel("Time per SDP solve (ms)")
    ax2.set_title("Cost per Objective Evaluation")
    ax2.xaxis.set_major_locator(MaxNLocator(integer=True))
    ax2.grid(True, alpha=0.3)
    
    plt.tight_layout()
    
    if save_path is not None:
        plt.savefig(save_path)
    if show:
        plt.show()
    
    return {
        "run_dir": run_dir,
        "k": ks_sorted,
        "avg_time_s": times,
        "avg_n_evals": evals,
        "time_per_eval_s": time_per_eval,
        "figure": fig,
        "axes": axes,
    }


def list_optimization_runs(
    *,
    results_root: Optional[Path] = None,
    model: Optional[str] = None,
    verbose: bool = True,
) -> List[Dict[str, Any]]:
    """List available optimization sweep runs.
    
    Args:
        results_root: Override default results directory.
        model: Filter by model name.
        verbose: If True, print a formatted table.
    
    Returns:
        List of run info dicts.
    """
    results_root = results_root or _default_results_root()
    
    runs = []
    for run_dir in _iter_run_dirs(results_root, "spin_optimization_sweep", 1):
        try:
            meta = _load_meta(run_dir)
        except Exception:
            continue
        
        if model is not None and meta.get("model") != model:
            continue

        L = meta.get("L", meta.get("adding_set_size"))

        k_values_present = meta.get("k_values_present")
        k_values_requested = meta.get("k_values_requested")

        # Prefer the actually-present k values; fall back to requested values.
        k_source = k_values_present or k_values_requested
        if isinstance(k_source, list) and len(k_source) > 0:
            try:
                k_min = int(min(k_source))
                k_max = int(max(k_source))
            except Exception:
                k_min, k_max = None, None
        else:
            k_min, k_max = None, None
        
        runs.append({
            "hash": run_dir.name,
            "model": meta.get("model"),
            "N": meta.get("N"),
            "boundary": meta.get("boundary"),
            "method": meta.get("method"),
            "start_level": meta.get("start_level"),
            "end_level": meta.get("end_level"),
            "L": L,
            "total_runs": meta.get("total_runs"),
            "k_values_present": k_values_present,
            "k_min": k_min,
            "k_max": k_max,
            "seeds_present": meta.get("seeds_present"),
            "updated_at": meta.get("updated_at"),
            "run_dir": run_dir,
        })
    
    if verbose and runs:
        print(f"{'Hash':<18} {'Model':<12} {'N':>3} {'Method':>6} {'L':>4} {'k':>9} {'Runs':>5} {'Updated':<20}")
        print("-" * 80)
        for r in runs:
            updated = r.get("updated_at", "")[:19] if r.get("updated_at") else ""
            k_range = ""
            if r.get("k_min") is not None and r.get("k_max") is not None:
                k_range = f"{r['k_min']}..{r['k_max']}"
            print(f"{r['hash']:<18} {r['model'] or '':<12} {r['N'] or '':>3} "
                  f"{r['method'] or '':>6} {r['L'] or '':>4} {k_range:>9} {r['total_runs'] or '':>5} {updated:<20}")
    elif verbose:
        print("No optimization sweep runs found.")
    
    return runs
